# Benchmarking

This benchmarking compares the PyTorch-native model variants (as opposed to the slowfast-based
MViTv2\_\*\_16x4/\_32x3 variants benchmarked in `sacair_2026/benchmark.ipynb`):
- S3D
- R3D_18
- R(2+1)D_18
- Swin3D_T
- Swin3D_S
- Swin3D_B
- MViTv2_S
- MViTv2_S_e
- MViTv1_B

each at 16 and/or 32 frames (models with interpolated positional encodings, suffix `_e`, use 32
frames; all others use 16, except the R3D/R(2+1)D/S3D/Swin3D families, which were benchmarked at
both), swept over batch size until each model OOMs -- the largest batch size shown per
model/frame-count/mode is therefore the last one that still fit.

During training, a stable GPU clock speed range of 1910 - 1930 MHz was recorded, so the GPU clock
speed is locked with a slight margin at 1900 with the command:
```bash
sudo nvidia-smi -lgc 1900
```
and can be reset with:
```bash
sudo nvidia-smi -rgc
```

In [1]:
import json

import pandas as pd

from src.run_types import RESULTS_DIR

In [2]:
def load_pytorch_benchmarks(benchmark_path):
    """
    Load the shared all_benchmark.json, keep only the PyTorch-native model variants (i.e. not
    the slowfast-based MViTv2_*_16x4/_32x3 variants covered by sacair_2026/benchmark.ipynb),
    drop OOM runs, map model names, and return separate DataFrames for training and inference.
    """
    with open(benchmark_path, "r") as f:
        raw = json.load(f)

    runs = raw["runs"]

    # Model name mapping
    model_name_map = {
        "S3D": "S3D",
        "R3D_18": "R3D\\_18",
        "R(2+1)D_18": "R(2+1)D\\_18",
        "Swin3D_T": "Swin3D\\_T",
        "Swin3D_S": "Swin3D\\_S",
        "Swin3D_B": "Swin3D\\_B",
        "MViTv2_S": "MViTv2\\_S",
        "MViTv2_S_e": "MViTv2\\_S\\_e",
        "MViTv1_B": "MViTv1\\_B",
    }

    records = []

    for run in runs.values():
        arch = run.get("arch", "")
        if arch not in model_name_map:
            continue
        if "error" in run:
            continue

        config = run["config"]
        results = run["results"]

        records.append({
            "model": model_name_map[arch],  # mapped name
            "num_frames": config["num_frames"],
            "mode": "Train" if config.get("full_step", False) else "Infer",
            "batch_size": config["batch_size"],

            "gpu_util_mean": results["gpu_utilisation_percent"]["mean"],
            "gpu_util_std": results["gpu_utilisation_percent"]["std"],

            "latency_ms_mean": results["latency_ms"]["mean"],
            "latency_ms_std": results["latency_ms"]["std"],

            "throughput_samp_per_s_mean": results["throughput_samples_per_s"]["mean"],
            "throughput_samp_per_s_std": results["throughput_samples_per_s"]["std"],

            "peak_mem_mb_mean": results["peak_memory_mb"]["mean"],
            "peak_mem_mb_std": results["peak_memory_mb"]["std"],
        })

    df = pd.DataFrame(records)

    metric_cols = [
        "gpu_util_mean", "gpu_util_std",
        "latency_ms_mean", "latency_ms_std",
        "throughput_samp_per_s_mean", "throughput_samp_per_s_std",
        "peak_mem_mb_mean", "peak_mem_mb_std",
    ]
    df[metric_cols] = df[metric_cols].round(2)

    # Sort by model, then num_frames, then batch_size
    train_df = df[df["mode"] == "Train"].sort_values(
        ["model", "num_frames", "batch_size"]
    ).reset_index(drop=True)
    infer_df = df[df["mode"] == "Infer"].sort_values(
        ["model", "num_frames", "batch_size"]
    ).reset_index(drop=True)

    return train_df, infer_df

## Load and display results

In [3]:
train_df, infer_df = load_pytorch_benchmarks(RESULTS_DIR / "all_benchmark.json")

print("Training DataFrame:")
display(train_df)

print("\nInference DataFrame:")
display(infer_df)

Training DataFrame:

,model,num_frames,mode,batch_size,gpu_util_mean,gpu_util_std,latency_ms_mean,latency_ms_std,throughput_samp_per_s_mean,throughput_samp_per_s_std,peak_mem_mb_mean,peak_mem_mb_std
0,MViTv1\_B,16,Train,1,99.99,0.02,127.93,0.11,7.82,0.01,1648.17,0.0
1,MViTv1\_B,16,Train,2,100.00,0.01,248.13,0.44,8.06,0.01,2952.42,0.0
2,MViTv1\_B,16,Train,4,100.00,0.00,471.92,0.16,8.48,0.00,5537.82,0.0
3,MViTv1\_B,16,Train,8,100.00,0.00,924.32,0.25,8.66,0.00,10707.35,0.0
4,MViTv2\_S,16,Train,1,98.66,0.02,175.50,0.39,5.70,0.01,1802.01,0.0
5,MViTv2\_S,16,Train,2,99.36,0.01,336.64,0.56,5.94,0.01,3294.64,0.0
6,MViTv2\_S,16,Train,4,99.79,0.02,643.22,0.72,6.22,0.01,6224.38,0.0
7,MViTv2\_S\_e,32,Train,1,99.49,0.01,427.50,0.65,2.34,0.00,3947.98,0.0
8,MViTv2\_S\_e,32,Train,2,99.87,0.01,837.06,0.92,2.39,0.00,7569.27,0.0
9,R(2+1)D\_18,16,Train,1,100.00,0.00,198.24,0.00,5.04,0.00,2274.04,0.0
10,R(2+1)D\_18,16,Train,2,100.00,0.01,384.91,0.01,5.20,0.00,4174.97,0.0
11,R(2+1)D\_18,16,Train,4,100.00,0.00,766.29,0.02,5.22,0.00,7998.13,0.0
12,R(2+1)D\_18,32,Train,1,100.00,0.00,384.94,0.01,2.60,0.00,4176.08,0.0
13,R(2+1)D\_18,32,Train,2,100.00,0.00,759.57,0.02,2.63,0.00,7994.02,0.0
14,R3D\_18,16,Train,1,99.99,0.02,129.96,0.01,7.69,0.00,1084.69,0.0
15,R3D\_18,16,Train,2,99.99,0.01,248.83,0.01,8.04,0.00,1751.10,0.0
16,R3D\_18,16,Train,4,100.00,0.00,494.70,0.06,8.09,0.00,3090.13,0.0
17,R3D\_18,16,Train,8,100.00,0.00,984.48,0.07,8.13,0.00,5829.45,0.0
18,R3D\_18,16,Train,16,100.00,0.00,1921.69,0.13,8.33,0.00,10834.67,0.0
19,R3D\_18,32,Train,1,100.00,0.00,249.15,0.00,4.01,0.00,1743.32,0.0
20,R3D\_18,32,Train,2,100.00,0.00,488.78,0.02,4.09,0.00,3093.22,0.0
21,R3D\_18,32,Train,4,100.00,0.00,983.07,0.07,4.07,0.00,5830.20,0.0
22,R3D\_18,32,Train,8,100.00,0.00,1929.67,0.14,4.15,0.00,10834.66,0.0
23,S3D,16,Train,1,99.97,0.07,31.46,0.00,31.79,0.00,546.84,0.0
24,S3D,16,Train,2,99.97,0.05,58.22,0.00,34.35,0.00,1012.14,0.0
25,S3D,16,Train,4,99.99,0.02,109.85,0.01,36.41,0.00,1945.76,0.0
26,S3D,16,Train,8,100.00,0.01,214.41,0.01,37.31,0.00,3821.83,0.0
27,S3D,16,Train,16,100.00,0.00,421.49,0.02,37.96,0.00,7568.14,0.0
28,S3D,32,Train,1,99.97,0.05,57.87,0.00,17.28,0.00,1010.27,0.0
29,S3D,32,Train,2,99.99,0.02,110.81,0.01,18.05,0.00,1945.76,0.0
30,S3D,32,Train,4,99.99,0.01,215.13,0.01,18.59,0.00,3821.50,0.0
31,S3D,32,Train,8,100.00,0.00,423.96,0.00,18.87,0.00,7565.88,0.0
32,Swin3D\_B,16,Train,1,100.00,0.01,291.57,0.17,3.43,0.00,3608.73,0.0
33,Swin3D\_B,16,Train,2,100.00,0.01,544.99,0.60,3.67,0.00,6378.34,0.0
34,Swin3D\_B,32,Train,1,100.00,0.00,546.65,0.92,1.83,0.00,6380.26,0.0
35,Swin3D\_S,16,Train,1,100.00,0.00,206.90,0.35,4.83,0.01,2573.02,0.0
36,Swin3D\_S,16,Train,2,100.00,0.00,383.05,0.65,5.22,0.01,4669.17,0.0
37,Swin3D\_S,16,Train,4,100.00,0.00,732.89,0.63,5.46,0.00,8870.82,0.0
38,Swin3D\_S,32,Train,1,100.00,0.00,387.24,0.85,2.58,0.01,4666.04,0.0
39,Swin3D\_S,32,Train,2,100.00,0.00,732.95,2.35,2.73,0.01,8870.61,0.0
40,Swin3D\_T,16,Train,1,99.97,0.02,120.12,0.21,8.33,0.01,1607.67,0.0
41,Swin3D\_T,16,Train,2,99.99,0.01,225.21,0.22,8.88,0.01,2925.25,0.0
42,Swin3D\_T,16,Train,4,100.00,0.00,431.77,0.06,9.26,0.00,5573.21,0.0
43,Swin3D\_T,16,Train,8,100.00,0.00,844.37,0.08,9.47,0.00,10868.02,0.0
44,Swin3D\_T,32,Train,1,100.00,0.00,227.65,0.20,4.39,0.00,2924.83,0.0
45,Swin3D\_T,32,Train,2,100.00,0.01,434.03,0.73,4.61,0.01,5569.59,0.0
46,Swin3D\_T,32,Train,4,100.00,0.00,846.62,0.95,4.72,0.01,10868.44,0.0

Inference DataFrame:

,model,num_frames,mode,batch_size,gpu_util_mean,gpu_util_std,latency_ms_mean,latency_ms_std,throughput_samp_per_s_mean,throughput_samp_per_s_std,peak_mem_mb_mean,peak_mem_mb_std
0,MViTv1\_B,16,Infer,1,100.0,0.0,40.50,0.03,24.69,0.02,363.52,0.0
1,MViTv1\_B,16,Infer,2,100.0,0.0,78.52,0.10,25.47,0.03,565.19,0.0
2,MViTv1\_B,16,Infer,4,100.0,0.0,154.79,0.18,25.84,0.03,971.71,0.0
3,MViTv1\_B,16,Infer,8,100.0,0.0,304.31,0.33,26.29,0.03,1785.24,0.0
4,MViTv1\_B,16,Infer,16,100.0,0.0,604.40,0.80,26.47,0.04,3410.42,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
74,Swin3D\_T,32,Infer,1,100.0,0.0,81.98,0.10,12.20,0.01,831.13,0.0
75,Swin3D\_T,32,Infer,2,100.0,0.0,155.34,0.15,12.88,0.01,1445.30,0.0
76,Swin3D\_T,32,Infer,4,100.0,0.0,300.14,0.07,13.33,0.00,2679.43,0.0
77,Swin3D\_T,32,Infer,8,100.0,0.0,592.68,0.56,13.50,0.01,5145.68,0.0
78,Swin3D\_T,32,Infer,16,100.0,0.0,1186.31,1.24,13.49,0.01,10064.18,0.0

### Prep for LaTeX

In [4]:
# Drop standard deviation columns and rename for table output
mean_cols = {
    "model": "Model",
    "num_frames": "Frames",
    "batch_size": "BS",
    "gpu_util_mean": "GPU Util.",
    "latency_ms_mean": "Latency (ms)",
    "throughput_samp_per_s_mean": "Throughput (samp/s)",
    "peak_mem_mb_mean": "Peak Mem. (MB)",
}

train_mean_df = train_df[list(mean_cols.keys())].rename(columns=mean_cols)
infer_mean_df = infer_df[list(mean_cols.keys())].rename(columns=mean_cols)

def format_benchmark_df(df):
    df = df.copy()
    df["GPU Util."] = df["GPU Util."].apply(lambda x: f"{x:.2f}\\%")
    df["Latency (ms)"] = df["Latency (ms)"].apply(lambda x: f"{x:,.2f}")
    df["Throughput (samp/s)"] = df["Throughput (samp/s)"].apply(lambda x: f"{x:,.2f}")
    df["Peak Mem. (MB)"] = df["Peak Mem. (MB)"].apply(lambda x: f"{x:,.2f}")
    return df

train_mean_df = format_benchmark_df(train_mean_df)
infer_mean_df = format_benchmark_df(infer_mean_df)

display(train_mean_df)
display(infer_mean_df)

,Model,Frames,BS,GPU Util.,Latency (ms),Throughput (samp/s),Peak Mem. (MB)
0,MViTv1\_B,16,1,99.99\%,127.93,7.82,"1,648.17"
1,MViTv1\_B,16,2,100.00\%,248.13,8.06,"2,952.42"
2,MViTv1\_B,16,4,100.00\%,471.92,8.48,"5,537.82"
3,MViTv1\_B,16,8,100.00\%,924.32,8.66,"10,707.35"
4,MViTv2\_S,16,1,98.66\%,175.50,5.70,"1,802.01"
5,MViTv2\_S,16,2,99.36\%,336.64,5.94,"3,294.64"
6,MViTv2\_S,16,4,99.79\%,643.22,6.22,"6,224.38"
7,MViTv2\_S\_e,32,1,99.49\%,427.50,2.34,"3,947.98"
8,MViTv2\_S\_e,32,2,99.87\%,837.06,2.39,"7,569.27"
9,R(2+1)D\_18,16,1,100.00\%,198.24,5.04,"2,274.04"
10,R(2+1)D\_18,16,2,100.00\%,384.91,5.20,"4,174.97"
11,R(2+1)D\_18,16,4,100.00\%,766.29,5.22,"7,998.13"
12,R(2+1)D\_18,32,1,100.00\%,384.94,2.60,"4,176.08"
13,R(2+1)D\_18,32,2,100.00\%,759.57,2.63,"7,994.02"
14,R3D\_18,16,1,99.99\%,129.96,7.69,"1,084.69"
15,R3D\_18,16,2,99.99\%,248.83,8.04,"1,751.10"
16,R3D\_18,16,4,100.00\%,494.70,8.09,"3,090.13"
17,R3D\_18,16,8,100.00\%,984.48,8.13,"5,829.45"
18,R3D\_18,16,16,100.00\%,"1,921.69",8.33,"10,834.67"
19,R3D\_18,32,1,100.00\%,249.15,4.01,"1,743.32"
20,R3D\_18,32,2,100.00\%,488.78,4.09,"3,093.22"
21,R3D\_18,32,4,100.00\%,983.07,4.07,"5,830.20"
22,R3D\_18,32,8,100.00\%,"1,929.67",4.15,"10,834.66"
23,S3D,16,1,99.97\%,31.46,31.79,546.84
24,S3D,16,2,99.97\%,58.22,34.35,"1,012.14"
25,S3D,16,4,99.99\%,109.85,36.41,"1,945.76"
26,S3D,16,8,100.00\%,214.41,37.31,"3,821.83"
27,S3D,16,16,100.00\%,421.49,37.96,"7,568.14"
28,S3D,32,1,99.97\%,57.87,17.28,"1,010.27"
29,S3D,32,2,99.99\%,110.81,18.05,"1,945.76"
30,S3D,32,4,99.99\%,215.13,18.59,"3,821.50"
31,S3D,32,8,100.00\%,423.96,18.87,"7,565.88"
32,Swin3D\_B,16,1,100.00\%,291.57,3.43,"3,608.73"
33,Swin3D\_B,16,2,100.00\%,544.99,3.67,"6,378.34"
34,Swin3D\_B,32,1,100.00\%,546.65,1.83,"6,380.26"
35,Swin3D\_S,16,1,100.00\%,206.90,4.83,"2,573.02"
36,Swin3D\_S,16,2,100.00\%,383.05,5.22,"4,669.17"
37,Swin3D\_S,16,4,100.00\%,732.89,5.46,"8,870.82"
38,Swin3D\_S,32,1,100.00\%,387.24,2.58,"4,666.04"
39,Swin3D\_S,32,2,100.00\%,732.95,2.73,"8,870.61"
40,Swin3D\_T,16,1,99.97\%,120.12,8.33,"1,607.67"
41,Swin3D\_T,16,2,99.99\%,225.21,8.88,"2,925.25"
42,Swin3D\_T,16,4,100.00\%,431.77,9.26,"5,573.21"
43,Swin3D\_T,16,8,100.00\%,844.37,9.47,"10,868.02"
44,Swin3D\_T,32,1,100.00\%,227.65,4.39,"2,924.83"
45,Swin3D\_T,32,2,100.00\%,434.03,4.61,"5,569.59"
46,Swin3D\_T,32,4,100.00\%,846.62,4.72,"10,868.44"

,Model,Frames,BS,GPU Util.,Latency (ms),Throughput (samp/s),Peak Mem. (MB)
0,MViTv1\_B,16,1,100.00\%,40.50,24.69,363.52
1,MViTv1\_B,16,2,100.00\%,78.52,25.47,565.19
2,MViTv1\_B,16,4,100.00\%,154.79,25.84,971.71
3,MViTv1\_B,16,8,100.00\%,304.31,26.29,"1,785.24"
4,MViTv1\_B,16,16,100.00\%,604.40,26.47,"3,410.42"
...,...,...,...,...,...,...,...
74,Swin3D\_T,32,1,100.00\%,81.98,12.20,831.13
75,Swin3D\_T,32,2,100.00\%,155.34,12.88,"1,445.30"
76,Swin3D\_T,32,4,100.00\%,300.14,13.33,"2,679.43"
77,Swin3D\_T,32,8,100.00\%,592.68,13.50,"5,145.68"
78,Swin3D\_T,32,16,100.00\%,"1,186.31",13.49,"10,064.18"

### Print LaTeX

In [5]:
def fixhlines(txt: str) -> str:
    return (
        txt.replace("\\toprule", "\\hline")
        .replace("\\midrule", "\\hline")
        .replace("\\bottomrule", "\\hline")
    )

In [6]:
train_latex = train_mean_df.to_latex(
    index=False,
    escape=False,
    column_format="|l|c|c|r|r|r|r|",
    caption="Training benchmark results for PyTorch-native model variants on an NVIDIA RTX 3060 12GB GPU.",
    label="tab:pytorch_benchmark_train",
    position="ht",
)

infer_latex = infer_mean_df.to_latex(
    index=False,
    escape=False,
    column_format="|l|c|c|r|r|r|r|",
    caption="Inference benchmark results for PyTorch-native model variants on an NVIDIA RTX 3060 12GB GPU.",
    label="tab:pytorch_benchmark_infer",
    position="ht",
)

print("Training Table LaTeX:")
print(fixhlines(train_latex))
print("\nInference Table LaTeX:")
print(fixhlines(infer_latex))

Training Table LaTeX:
\begin{table}[ht]
\caption{Training benchmark results for PyTorch-native model variants on an NVIDIA RTX 3060 12GB GPU.}
\label{tab:pytorch_benchmark_train}
\begin{tabular}{|l|c|c|r|r|r|r|}
\hline
Model & Frames & BS & GPU Util. & Latency (ms) & Throughput (samp/s) & Peak Mem. (MB) \\
\hline
MViTv1\_B & 16 & 1 & 99.99\% & 127.93 & 7.82 & 1,648.17 \\
MViTv1\_B & 16 & 2 & 100.00\% & 248.13 & 8.06 & 2,952.42 \\
MViTv1\_B & 16 & 4 & 100.00\% & 471.92 & 8.48 & 5,537.82 \\
MViTv1\_B & 16 & 8 & 100.00\% & 924.32 & 8.66 & 10,707.35 \\
MViTv2\_S & 16 & 1 & 98.66\% & 175.50 & 5.70 & 1,802.01 \\
MViTv2\_S & 16 & 2 & 99.36\% & 336.64 & 5.94 & 3,294.64 \\
MViTv2\_S & 16 & 4 & 99.79\% & 643.22 & 6.22 & 6,224.38 \\
MViTv2\_S\_e & 32 & 1 & 99.49\% & 427.50 & 2.34 & 3,947.98 \\
MViTv2\_S\_e & 32 & 2 & 99.87\% & 837.06 & 2.39 & 7,569.27 \\
R(2+1)D\_18 & 16 & 1 & 100.00\% & 198.24 & 5.04 & 2,274.04 \\
R(2+1)D\_18 & 16 & 2 & 100.00\% & 384.91 & 5.20 & 4,174.97 \\
R(2+1)D\_18 & 16 & 4 & 100.00\% & 766.29 & 5.22 & 7,998.13 \\
R(2+1)D\_18 & 32 & 1 & 100.00\% & 384.94 & 2.60 & 4,176.08 \\
R(2+1)D\_18 & 32 & 2 & 100.00\% & 759.57 & 2.63 & 7,994.02 \\
R3D\_18 & 16 & 1 & 99.99\% & 129.96 & 7.69 & 1,084.69 \\
R3D\_18 & 16 & 2 & 99.99\% & 248.83 & 8.04 & 1,751.10 \\
R3D\_18 & 16 & 4 & 100.00\% & 494.70 & 8.09 & 3,090.13 \\
R3D\_18 & 16 & 8 & 100.00\% & 984.48 & 8.13 & 5,829.45 \\
R3D\_18 & 16 & 16 & 100.00\% & 1,921.69 & 8.33 & 10,834.67 \\
R3D\_18 & 32 & 1 & 100.00\% & 249.15 & 4.01 & 1,743.32 \\
R3D\_18 & 32 & 2 & 100.00\% & 488.78 & 4.09 & 3,093.22 \\
R3D\_18 & 32 & 4 & 100.00\% & 983.07 & 4.07 & 5,830.20 \\
R3D\_18 & 32 & 8 & 100.00\% & 1,929.67 & 4.15 & 10,834.66 \\
S3D & 16 & 1 & 99.97\% & 31.46 & 31.79 & 546.84 \\
S3D & 16 & 2 & 99.97\% & 58.22 & 34.35 & 1,012.14 \\
S3D & 16 & 4 & 99.99\% & 109.85 & 36.41 & 1,945.76 \\
S3D & 16 & 8 & 100.00\% & 214.41 & 37.31 & 3,821.83 \\
S3D & 16 & 16 & 100.00\% & 421.49 & 37.96 & 7,568.14 \\
S3D & 32 & 1 & 99.97\% & 57.87 & 17.28 & 1,010.27 \\
S3D & 32 & 2 & 99.99\% & 110.81 & 18.05 & 1,945.76 \\
S3D & 32 & 4 & 99.99\% & 215.13 & 18.59 & 3,821.50 \\
S3D & 32 & 8 & 100.00\% & 423.96 & 18.87 & 7,565.88 \\
Swin3D\_B & 16 & 1 & 100.00\% & 291.57 & 3.43 & 3,608.73 \\
Swin3D\_B & 16 & 2 & 100.00\% & 544.99 & 3.67 & 6,378.34 \\
Swin3D\_B & 32 & 1 & 100.00\% & 546.65 & 1.83 & 6,380.26 \\
Swin3D\_S & 16 & 1 & 100.00\% & 206.90 & 4.83 & 2,573.02 \\
Swin3D\_S & 16 & 2 & 100.00\% & 383.05 & 5.22 & 4,669.17 \\
Swin3D\_S & 16 & 4 & 100.00\% & 732.89 & 5.46 & 8,870.82 \\
Swin3D\_S & 32 & 1 & 100.00\% & 387.24 & 2.58 & 4,666.04 \\
Swin3D\_S & 32 & 2 & 100.00\% & 732.95 & 2.73 & 8,870.61 \\
Swin3D\_T & 16 & 1 & 99.97\% & 120.12 & 8.33 & 1,607.67 \\
Swin3D\_T & 16 & 2 & 99.99\% & 225.21 & 8.88 & 2,925.25 \\
Swin3D\_T & 16 & 4 & 100.00\% & 431.77 & 9.26 & 5,573.21 \\
Swin3D\_T & 16 & 8 & 100.00\% & 844.37 & 9.47 & 10,868.02 \\
Swin3D\_T & 32 & 1 & 100.00\% & 227.65 & 4.39 & 2,924.83 \\
Swin3D\_T & 32 & 2 & 100.00\% & 434.03 & 4.61 & 5,569.59 \\
Swin3D\_T & 32 & 4 & 100.00\% & 846.62 & 4.72 & 10,868.44 \\
\hline
\end{tabular}
\end{table}


Inference Table LaTeX:
\begin{table}[ht]
\caption{Inference benchmark results for PyTorch-native model variants on an NVIDIA RTX 3060 12GB GPU.}
\label{tab:pytorch_benchmark_infer}
\begin{tabular}{|l|c|c|r|r|r|r|}
\hline
Model & Frames & BS & GPU Util. & Latency (ms) & Throughput (samp/s) & Peak Mem. (MB) \\
\hline
MViTv1\_B & 16 & 1 & 100.00\% & 40.50 & 24.69 & 363.52 \\
MViTv1\_B & 16 & 2 & 100.00\% & 78.52 & 25.47 & 565.19 \\
MViTv1\_B & 16 & 4 & 100.00\% & 154.79 & 25.84 & 971.71 \\
MViTv1\_B & 16 & 8 & 100.00\% & 304.31 & 26.29 & 1,785.24 \\
MViTv1\_B & 16 & 16 & 100.00\% & 604.40 & 26.47 & 3,410.42 \\
MViTv1\_B & 16 & 32 & 100.00\% & 1,219.09 & 26.25 & 6,655.60 \\
MViTv2\_S & 16 & 1 & 98.00\% & 50.75 & 19.70 & 417.83 \\
MViTv2\_S & 16 & 2 & 99.00\% & 97.85 & 20.44 & 680.53 \\
MViTv2\_S & 16 & 4 & 99.65\% & 192.34 & 20.80 & 1,212.29 \\
MViTv2\_S & 16 & 8 & 100.00\% & 377.86 & 21.17 & 2,277.22 \\
MViTv2\_S & 16 & 16 & 100.00\% & 750.87 & 21.31 & 4,406.08 \\
MViTv2\_S\_e & 32 & 1 & 99.01\% & 127.40 & 7.85 & 1,134.06 \\
MViTv2\_S\_e & 32 & 2 & 99.84\% & 252.48 & 7.92 & 2,114.95 \\
MViTv2\_S\_e & 32 & 4 & 100.00\% & 497.04 & 8.05 & 4,081.24 \\
MViTv2\_S\_e & 32 & 8 & 100.00\% & 986.99 & 8.11 & 8,015.75 \\
R(2+1)D\_18 & 16 & 1 & 100.00\% & 56.27 & 17.77 & 562.68 \\
R(2+1)D\_18 & 16 & 2 & 100.00\% & 108.90 & 18.37 & 988.37 \\
R(2+1)D\_18 & 16 & 4 & 100.00\% & 214.99 & 18.61 & 1,841.64 \\
R(2+1)D\_18 & 16 & 8 & 100.00\% & 463.09 & 17.28 & 3,150.89 \\
R(2+1)D\_18 & 16 & 16 & 100.00\% & 844.58 & 18.94 & 6,948.99 \\
R(2+1)D\_18 & 32 & 1 & 100.00\% & 109.17 & 9.16 & 987.47 \\
R(2+1)D\_18 & 32 & 2 & 100.00\% & 215.83 & 9.27 & 1,840.73 \\
R(2+1)D\_18 & 32 & 4 & 100.00\% & 463.92 & 8.62 & 3,149.98 \\
R(2+1)D\_18 & 32 & 8 & 100.00\% & 847.44 & 9.44 & 6,948.09 \\
R3D\_18 & 16 & 1 & 100.00\% & 34.60 & 28.91 & 401.13 \\
R3D\_18 & 16 & 2 & 100.00\% & 66.89 & 29.90 & 655.31 \\
R3D\_18 & 16 & 4 & 100.00\% & 132.41 & 30.21 & 1,163.69 \\
R3D\_18 & 16 & 8 & 100.00\% & 262.60 & 30.46 & 2,180.94 \\
R3D\_18 & 16 & 16 & 100.00\% & 522.08 & 30.65 & 4,214.94 \\
R3D\_18 & 16 & 32 & 100.00\% & 1,042.30 & 30.70 & 8,280.94 \\
R3D\_18 & 32 & 1 & 100.00\% & 66.99 & 14.93 & 655.31 \\
R3D\_18 & 32 & 2 & 100.00\% & 132.34 & 15.11 & 1,163.69 \\
R3D\_18 & 32 & 4 & 100.00\% & 263.40 & 15.19 & 2,180.94 \\
R3D\_18 & 32 & 8 & 100.00\% & 523.40 & 15.28 & 4,214.94 \\
R3D\_18 & 32 & 16 & 100.00\% & 1,043.04 & 15.34 & 8,280.94 \\
S3D & 16 & 1 & 100.00\% & 9.86 & 101.44 & 163.19 \\
S3D & 16 & 2 & 100.00\% & 18.15 & 110.20 & 294.23 \\
S3D & 16 & 4 & 100.00\% & 35.01 & 114.26 & 557.60 \\
S3D & 16 & 8 & 100.00\% & 68.27 & 117.18 & 1,084.85 \\
S3D & 16 & 16 & 100.00\% & 134.77 & 118.72 & 2,138.85 \\
S3D & 16 & 32 & 100.00\% & 267.07 & 119.82 & 4,244.85 \\
S3D & 16 & 64 & 100.00\% & 532.30 & 120.23 & 8,458.85 \\
S3D & 32 & 1 & 100.00\% & 18.27 & 54.73 & 294.38 \\
S3D & 32 & 2 & 100.00\% & 35.21 & 56.80 & 557.60 \\
S3D & 32 & 4 & 100.00\% & 68.87 & 58.08 & 1,084.85 \\
S3D & 32 & 8 & 100.00\% & 135.90 & 58.87 & 2,138.85 \\
S3D & 32 & 16 & 100.00\% & 269.43 & 59.38 & 4,244.85 \\
S3D & 32 & 32 & 100.00\% & 536.51 & 59.65 & 8,458.85 \\
Swin3D\_B & 16 & 1 & 100.00\% & 104.00 & 9.62 & 836.37 \\
Swin3D\_B & 16 & 2 & 100.00\% & 190.67 & 10.49 & 1,242.87 \\
Swin3D\_B & 16 & 4 & 100.00\% & 368.93 & 10.84 & 2,062.99 \\
Swin3D\_B & 16 & 8 & 100.00\% & 719.07 & 11.13 & 3,686.74 \\
Swin3D\_B & 16 & 16 & 100.00\% & 1,426.57 & 11.22 & 6,947.74 \\
Swin3D\_B & 32 & 1 & 100.00\% & 193.61 & 5.17 & 1,283.30 \\
Swin3D\_B & 32 & 2 & 100.00\% & 372.36 & 5.37 & 2,099.34 \\
Swin3D\_B & 32 & 4 & 100.00\% & 722.87 & 5.53 & 3,723.09 \\
Swin3D\_B & 32 & 8 & 100.00\% & 1,432.46 & 5.58 & 6,984.09 \\
Swin3D\_S & 16 & 1 & 100.00\% & 73.03 & 13.69 & 585.34 \\
Swin3D\_S & 16 & 2 & 100.00\% & 134.19 & 14.90 & 895.81 \\
Swin3D\_S & 16 & 4 & 100.00\% & 257.49 & 15.53 & 1,508.68 \\
Swin3D\_S & 16 & 8 & 100.00\% & 499.19 & 16.03 & 2,742.81 \\
Swin3D\_S & 16 & 16 & 100.00\% & 987.76 & 16.20 & 5,209.06 \\
Swin3D\_S & 16 & 32 & 100.00\% & 1,979.36 & 16.17 & 10,127.56 \\
Swin3D\_S & 32 & 1 & 100.00\% & 136.97 & 7.30 & 932.00 \\
Swin3D\_S & 32 & 2 & 100.00\% & 260.89 & 7.67 & 1,546.50 \\
Swin3D\_S & 32 & 4 & 100.00\% & 502.92 & 7.95 & 2,780.63 \\
Swin3D\_S & 32 & 8 & 100.00\% & 992.99 & 8.06 & 5,246.88 \\
Swin3D\_S & 32 & 16 & 100.00\% & 1,990.36 & 8.04 & 10,165.38 \\
Swin3D\_T & 16 & 1 & 100.00\% & 42.98 & 23.27 & 486.60 \\
Swin3D\_T & 16 & 2 & 100.00\% & 79.47 & 25.17 & 797.07 \\
Swin3D\_T & 16 & 4 & 100.00\% & 152.31 & 26.26 & 1,409.94 \\
Swin3D\_T & 16 & 8 & 100.00\% & 296.31 & 27.00 & 2,644.07 \\
Swin3D\_T & 16 & 16 & 100.00\% & 587.00 & 27.26 & 5,110.32 \\
Swin3D\_T & 16 & 32 & 100.00\% & 1,174.92 & 27.24 & 10,028.82 \\
Swin3D\_T & 32 & 1 & 100.00\% & 81.98 & 12.20 & 831.13 \\
Swin3D\_T & 32 & 2 & 100.00\% & 155.34 & 12.88 & 1,445.30 \\
Swin3D\_T & 32 & 4 & 100.00\% & 300.14 & 13.33 & 2,679.43 \\
Swin3D\_T & 32 & 8 & 100.00\% & 592.68 & 13.50 & 5,145.68 \\
Swin3D\_T & 32 & 16 & 100.00\% & 1,186.31 & 13.49 & 10,064.18 \\
\hline
\end{tabular}
\end{table}